apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: auwrun4zl-nodejs
  janus-idp.io/tekton: auwrun4zl-nodejs
  backstage.io/kubernetes-id: auwrun4zl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: auwrun4zl-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
