apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: auwrun4zl-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:6e2240df76a46d0fca886a90cc28e0002ea7375d@sha256:6aa15df4b0256d5ccd6b6f5b1f6caac48be09161976d19da33e5b1035e2f7d8a
          name: container-image
